ALTER TABLE "SolarScan" ADD COLUMN IF NOT EXISTS "aiHealthScore" INTEGER;
ALTER TABLE "SolarScan" ADD COLUMN IF NOT EXISTS "aiRecommendation" TEXT;
ALTER TABLE "SolarScan" ADD COLUMN IF NOT EXISTS "aiSummary" TEXT;
ALTER TABLE "SolarScan" ADD COLUMN IF NOT EXISTS "aiRootCause" TEXT;
ALTER TABLE "SolarScan" ADD COLUMN IF NOT EXISTS "aiImpactAssessment" TEXT;
ALTER TABLE "SolarScan" ADD COLUMN IF NOT EXISTS "aiTimeframe" TEXT;
ALTER TABLE "SolarScan" ADD COLUMN IF NOT EXISTS "aiSource" TEXT;
ALTER TABLE "SolarScan" ADD COLUMN IF NOT EXISTS "aiBaselineAware" BOOLEAN;
ALTER TABLE "SolarScan" ADD COLUMN IF NOT EXISTS "aiDeviationFromBaseline" TEXT;
ALTER TABLE "SolarScan" ADD COLUMN IF NOT EXISTS "aiGenaiInsights" TEXT;

ALTER TABLE "PanelDetection" ADD COLUMN IF NOT EXISTS "thermalCropImageUrl" TEXT;
